/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.group4.RISK.server;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;

public class HostApp {

    private ServerSocket hostSocket;
    private int playerNum;

    public HostApp(ServerSocket socket,int playerNum) {
        this.hostSocket=socket;
        this.playerNum=playerNum;

    }


    private void connectClients() throws IOException {
        int count=this.playerNum;
        while(count > 0){
            Socket s = hostSocket.accept();
//            ClientThread = new ClientThread(theworld, new Client(s));
//            ClientThread.run();
            count --;
        }
    }

    public static void main(String[] args) {
        String instruct1 = "Please enter the Player Number";
        BufferedReader inRead=new BufferedReader(new InputStreamReader(System.in));


        int playerNum=0;
        while (playerNum!=0) {
            try {
                System.out.println(instruct1);
                String playerNumRead = inRead.readLine();
                if(!isNumeric(playerNumRead)){
                    throw new IllegalArgumentException();
                }
                playerNum=Integer.parseInt(playerNumRead);

            }catch(Exception e){
                System.out.println("Please enter correct number!");
            }
        }




    }

    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(strNum);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
}
