///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package edu.duke.ece651.group4.RISK.client;
//
//
//import edu.duke.ece651.group4.RISK.shared.Troop;
//
//import java.net.Socket;
//
//public class PlayerApp {
//    private Socket mySocket;
//
//    public PlayerApp(){
//
//    }
//
//    public static void main(String[] args){
//
//    }
//}
