/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.group4.RISK;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HostAppTest {
    @Test void appHasAGreeting() {
        HostApp classUnderTest = new HostApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}












